import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const defaultFont = localFont({
  src: "../public/fonts/Satoshi-Regular.otf",
});

const headingFont = localFont({
  src: "../public/fonts/Bevellier-Medium.otf",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${defaultFont.className} ${headingFont.variable} antialiased overflow-x-hidden min-h-dvh`}
      >
        {children}
      </body>
    </html>
  );
}
